# v2 syntax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  ninjas-mysql-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: ninjas-mysql
    volumes:
      - ninjas-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=ninjas
      - MYSQL_DATABASE=ninjas
      - MYSQL_USER=ninjas
      - MYSQL_PASSWORD=ninjas

  # PHP 7.3 + nginx
  app:
    image: ambientum/php:latest-nginx
    container_name: ninjas-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - mysql